### ISSUE TITLE
Receiving "We are sorry to exception happened kotlin.KotlinNullPointerException type exception" on some files

### ISSUE THREAD

**Issue by drajovic** [GDNext-GmbH/polybpmn#8]
**Describe the bug**
On some BPMN files the kotlin.KotlinNullPointerException exception is thrown

**To Reproduce**
1. Click on file
2. See error (instead of diagram)

**BPMN definition**
sorry, cannot disclose

**Expected behavior**
A diagram should have been shown.
There is nothing obvious to be fixed in the diagram (Camunda Modeler and Camunda BPM Visualiser can display the diagram) so saving the file is of no help.

**Displayed error**
Uh, oh... Problem while initializing plugin. Try fixing and clicking Ctrl+S to save the file
kotlin.KotlinNullPointerException
	at com.gdnext.bpmn.intellij.plugin.core.l.c.c(Unknown Source)
	at com.gdnext.bpmn.intellij.plugin.core.l.c.a(Unknown Source)
	at com.gdnext.bpmn.intellij.plugin.core.l.c.a(Unknown Source)
	at com.gdnext.bpmn.intellij.plugin.core.render.h.a(Unknown Source)
	at com.gdnext.bpmn.intellij.plugin.core.C.a(Unknown Source)
	at com.gdnext.bpmn.intellij.plugin.core.b.a(Unknown Source)
	at com.gdnext.bpmn.intellij.plugin.camunda.a.a(Unknown Source)
	at com.gdnext.bpmn.intellij.plugin.polybpmn.c.b(Unknown Source)
	at com.gdnext.bpmn.intellij.plugin.polybpmn.c.a(Unknown Source)
	at com.gdnext.bpmn.intellij.plugin.core.c.d.run(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:428)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:115)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:478)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:251)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:251)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:465)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

**IntelliJ version (please complete the following information):**
 - Edition: Ultimate
 - Version: 2023.2,  Build #IU-232.8660.185
 
**Additional context**

**Comment by valb3r** [comment]
@drajovic Thanks for feedback, 

Maybe you have noticed that there are some peculiarities about the file you are opening (like special boundary event present)?

**Comment by drajovic** [comment]
Yes, Camunda BPMN Visualizer plugin can show the diagram. I am using v0.5.4.2.Am 23.08.2023 um 11:09 schrieb Valentyn Berezin ***@***.***>:﻿
@drajovic Thanks for feedback, can you please try to open the file using open-source plugin https://plugins.jetbrains.com/plugin/17844-camunda-bpmn-visualizer
Or maybe you have noticed that there are some peculiarities about the file you are opening (like special boundary event present)?

**Comment by drajovic** [comment]
Yes, it seems to be related to pools and lines, in fact, only lines. However, it is not easy to reproduce. I succeeded in creating a NOK file (will throw an exception) by adding a middle lane in an OK file (parses fine). See the two examples below. 

While doing some other changes in a NOK file (e.g. renaming pools, lanes, etc.) I was able to produce another error. Your editor for the bpmn files just freezes. It does not update the diagram. The changes made outside (e.g. Camunda Modeler) do not get refreshed inside IntelliJ. One cannot even close the open tab for that file in IntelliJ. The editor appears to be dead (no exceptions thrown inside IntelliJ GUI). This behavior also seems to be related to pools/lanes (I was changing their names/properties) but it's different - the editor does not throw the error, it freezes.

So, here's the test data to reproduce the first error. An OK and a NOK diagram with only one lane added in Camunda Modeler.

**OK diagram**

```xml
<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:zeebe="http://camunda.org/schema/zeebe/1.0" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:modeler="http://camunda.org/schema/modeler/1.0" id="Definitions_0irw2wy" targetNamespace="http://bpmn.io/schema/bpmn" exporter="Camunda Modeler" exporterVersion="5.14.0" modeler:executionPlatform="Camunda Cloud" modeler:executionPlatformVersion="8.1.0">
  <bpmn:collaboration id="Collaboration_1f5vyps">
    <bpmn:participant id="Participant_18hshoa" name="Foo" processRef="Process_05n6x8d" />
    <bpmn:participant id="Participant_1lcoo0m" name="Bar" processRef="Process_0bshks3" />
    <bpmn:participant id="Participant_1donwvr" name="Baz" processRef="Process_056kd6t" />
    <bpmn:participant id="Participant_1f918a5" name="Boom" processRef="Process_0vqqg2m" />
    <bpmn:group id="Group_0w380le" />
    <bpmn:textAnnotation id="TextAnnotation_1lkonc6">
      <bpmn:text>Blah blah</bpmn:text>
    </bpmn:textAnnotation>
    <bpmn:association id="Association_1dkfaiy" sourceRef="Participant_18hshoa" targetRef="TextAnnotation_1lkonc6" />
    <bpmn:textAnnotation id="TextAnnotation_0nt8b2x">
      <bpmn:text>Tralala</bpmn:text>
    </bpmn:textAnnotation>
    <bpmn:association id="Association_1i0bouy" sourceRef="Group_0w380le" targetRef="TextAnnotation_0nt8b2x" />
  </bpmn:collaboration>
  <bpmn:process id="Process_05n6x8d" isExecutable="true">
    <bpmn:documentation />
    <bpmn:laneSet id="LaneSet_1jared5">
      <bpmn:lane id="Lane_0z9w44w" name="Bim">
        <bpmn:flowNodeRef>StartEvent_1</bpmn:flowNodeRef>
        <bpmn:flowNodeRef>Event_0u482rl</bpmn:flowNodeRef>
        <bpmn:flowNodeRef>Activity_0b1ftek</bpmn:flowNodeRef>
        <bpmn:flowNodeRef>Activity_0c2ay3h</bpmn:flowNodeRef>
      </bpmn:lane>
      <bpmn:lane id="Lane_1gatmwv" name="Bam">
        <bpmn:flowNodeRef>Activity_0svk239</bpmn:flowNodeRef>
      </bpmn:lane>
    </bpmn:laneSet>
    <bpmn:startEvent id="StartEvent_1">
      <bpmn:outgoing>Flow_15ks01v</bpmn:outgoing>
    </bpmn:startEvent>
    <bpmn:endEvent id="Event_0u482rl">
      <bpmn:incoming>Flow_02rfwbg</bpmn:incoming>
    </bpmn:endEvent>
    <bpmn:callActivity id="Activity_0b1ftek" name="AA">
      <bpmn:extensionElements>
        <zeebe:calledElement processId="Process_0bshks3" propagateAllChildVariables="false" />
      </bpmn:extensionElements>
      <bpmn:incoming>Flow_15ks01v</bpmn:incoming>
      <bpmn:outgoing>Flow_1ctkn2b</bpmn:outgoing>
    </bpmn:callActivity>
    <bpmn:callActivity id="Activity_0svk239" name="BB">
      <bpmn:extensionElements>
        <zeebe:calledElement processId="Process_056kd6t" propagateAllChildVariables="false" />
      </bpmn:extensionElements>
      <bpmn:incoming>Flow_1ctkn2b</bpmn:incoming>
      <bpmn:outgoing>Flow_0d81f97</bpmn:outgoing>
    </bpmn:callActivity>
    <bpmn:callActivity id="Activity_0c2ay3h" name="CC">
      <bpmn:extensionElements>
        <zeebe:calledElement processId="Process_0vqqg2m" propagateAllChildVariables="false" />
      </bpmn:extensionElements>
      <bpmn:incoming>Flow_0d81f97</bpmn:incoming>
      <bpmn:outgoing>Flow_02rfwbg</bpmn:outgoing>
    </bpmn:callActivity>
    <bpmn:sequenceFlow id="Flow_15ks01v" sourceRef="StartEvent_1" targetRef="Activity_0b1ftek" />
    <bpmn:sequenceFlow id="Flow_02rfwbg" sourceRef="Activity_0c2ay3h" targetRef="Event_0u482rl" />
    <bpmn:sequenceFlow id="Flow_1ctkn2b" sourceRef="Activity_0b1ftek" targetRef="Activity_0svk239" />
    <bpmn:sequenceFlow id="Flow_0d81f97" sourceRef="Activity_0svk239" targetRef="Activity_0c2ay3h" />
  </bpmn:process>
  <bpmn:process id="Process_0bshks3" isExecutable="true">
    <bpmn:serviceTask id="Activity_10mlpa0" name="A">
      <bpmn:extensionElements>
        <zeebe:taskDefinition type="bar" />
        <zeebe:ioMapping>
          <zeebe:input source="" target="env" />
          <zeebe:input source="" target="app" />
        </zeebe:ioMapping>
      </bpmn:extensionElements>
    </bpmn:serviceTask>
  </bpmn:process>
  <bpmn:process id="Process_056kd6t" isExecutable="true">
    <bpmn:serviceTask id="Activity_1t5cglo" name="B">
      <bpmn:extensionElements>
        <zeebe:taskDefinition type="foo" />
      </bpmn:extensionElements>
    </bpmn:serviceTask>
  </bpmn:process>
  <bpmn:process id="Process_0vqqg2m" isExecutable="true">
    <bpmn:serviceTask id="Activity_1v6pb87" name="C">
      <bpmn:extensionElements>
        <zeebe:taskDefinition type="bar" />
      </bpmn:extensionElements>
    </bpmn:serviceTask>
  </bpmn:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Collaboration_1f5vyps">
      <bpmndi:BPMNShape id="Participant_18hshoa_di" bpmnElement="Participant_18hshoa" isHorizontal="true">
        <dc:Bounds x="249" y="190" width="839" height="250" />
        <bpmndi:BPMNLabel />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Lane_1gatmwv_di" bpmnElement="Lane_1gatmwv" isHorizontal="true">
        <dc:Bounds x="279" y="315" width="809" height="125" />
        <bpmndi:BPMNLabel />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Lane_0z9w44w_di" bpmnElement="Lane_0z9w44w" isHorizontal="true">
        <dc:Bounds x="279" y="190" width="809" height="125" />
        <bpmndi:BPMNLabel />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="_BPMNShape_StartEvent_2" bpmnElement="StartEvent_1">
        <dc:Bounds x="382" y="232" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_0u482rl_di" bpmnElement="Event_0u482rl">
        <dc:Bounds x="952" y="232" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_0n99hl5_di" bpmnElement="Activity_0b1ftek">
        <dc:Bounds x="470" y="210" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_1kihcv5_di" bpmnElement="Activity_0svk239">
        <dc:Bounds x="630" y="340" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_0dkd24a_di" bpmnElement="Activity_0c2ay3h">
        <dc:Bounds x="790" y="210" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="Flow_15ks01v_di" bpmnElement="Flow_15ks01v">
        <di:waypoint x="418" y="250" />
        <di:waypoint x="470" y="250" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_02rfwbg_di" bpmnElement="Flow_02rfwbg">
        <di:waypoint x="890" y="250" />
        <di:waypoint x="952" y="250" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1ctkn2b_di" bpmnElement="Flow_1ctkn2b">
        <di:waypoint x="570" y="250" />
        <di:waypoint x="600" y="250" />
        <di:waypoint x="600" y="380" />
        <di:waypoint x="630" y="380" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_0d81f97_di" bpmnElement="Flow_0d81f97">
        <di:waypoint x="730" y="380" />
        <di:waypoint x="760" y="380" />
        <di:waypoint x="760" y="250" />
        <di:waypoint x="790" y="250" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape id="Participant_1lcoo0m_di" bpmnElement="Participant_1lcoo0m" isHorizontal="true">
        <dc:Bounds x="210" y="580" width="301" height="120" />
        <bpmndi:BPMNLabel />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_1pprjxf_di" bpmnElement="Activity_10mlpa0">
        <dc:Bounds x="311" y="600" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Participant_1donwvr_di" bpmnElement="Participant_1donwvr" isHorizontal="true">
        <dc:Bounds x="541" y="580" width="300" height="120" />
        <bpmndi:BPMNLabel />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_048iti1_di" bpmnElement="Activity_1t5cglo">
        <dc:Bounds x="651" y="600" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Participant_1f918a5_di" bpmnElement="Participant_1f918a5" isHorizontal="true">
        <dc:Bounds x="871" y="580" width="300" height="120" />
        <bpmndi:BPMNLabel />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_1fxhjok_di" bpmnElement="Activity_1v6pb87">
        <dc:Bounds x="981" y="600" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Group_0w380le_di" bpmnElement="Group_0w380le">
        <dc:Bounds x="160" y="550" width="1060" height="180" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="TextAnnotation_1lkonc6_di" bpmnElement="TextAnnotation_1lkonc6">
        <dc:Bounds x="380" y="80" width="570" height="26" />
        <bpmndi:BPMNLabel />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="TextAnnotation_0nt8b2x_di" bpmnElement="TextAnnotation_0nt8b2x">
        <dc:Bounds x="340" y="470" width="679" height="26" />
        <bpmndi:BPMNLabel />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="Association_1dkfaiy_di" bpmnElement="Association_1dkfaiy">
        <di:waypoint x="669" y="316" />
        <di:waypoint x="665" y="201" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Association_1i0bouy_di" bpmnElement="Association_1i0bouy">
        <di:waypoint x="690" y="639" />
        <di:waypoint x="680" y="574" />
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>
```
 
**NOK diagram**

```xml
<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:zeebe="http://camunda.org/schema/zeebe/1.0" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:modeler="http://camunda.org/schema/modeler/1.0" id="Definitions_0irw2wy" targetNamespace="http://bpmn.io/schema/bpmn" exporter="Camunda Modeler" exporterVersion="5.14.0" modeler:executionPlatform="Camunda Cloud" modeler:executionPlatformVersion="8.1.0">
  <bpmn:collaboration id="Collaboration_1f5vyps">
    <bpmn:participant id="Participant_18hshoa" name="Foo" processRef="Process_05n6x8d" />
    <bpmn:participant id="Participant_1lcoo0m" name="Bar" processRef="Process_0bshks3" />
    <bpmn:participant id="Participant_1donwvr" name="Baz" processRef="Process_056kd6t" />
    <bpmn:participant id="Participant_1f918a5" name="Boom" processRef="Process_0vqqg2m" />
    <bpmn:group id="Group_0w380le" />
    <bpmn:textAnnotation id="TextAnnotation_1lkonc6">
      <bpmn:text>Blah blah</bpmn:text>
    </bpmn:textAnnotation>
    <bpmn:association id="Association_1dkfaiy" sourceRef="Participant_18hshoa" targetRef="TextAnnotation_1lkonc6" />
    <bpmn:textAnnotation id="TextAnnotation_0nt8b2x">
      <bpmn:text>Tralala</bpmn:text>
    </bpmn:textAnnotation>
    <bpmn:association id="Association_1i0bouy" sourceRef="Group_0w380le" targetRef="TextAnnotation_0nt8b2x" />
  </bpmn:collaboration>
  <bpmn:process id="Process_05n6x8d" isExecutable="true">
    <bpmn:documentation></bpmn:documentation>
    <bpmn:laneSet id="LaneSet_1jared5">
      <bpmn:lane id="Lane_1gatmwv" name="Bam">
        <bpmn:flowNodeRef>Activity_0svk239</bpmn:flowNodeRef>
      </bpmn:lane>
      <bpmn:lane id="Lane_0z9w44w" name="Bim">
        <bpmn:flowNodeRef>StartEvent_1</bpmn:flowNodeRef>
        <bpmn:flowNodeRef>Event_0u482rl</bpmn:flowNodeRef>
        <bpmn:flowNodeRef>Activity_0b1ftek</bpmn:flowNodeRef>
        <bpmn:flowNodeRef>Activity_0c2ay3h</bpmn:flowNodeRef>
      </bpmn:lane>
      <bpmn:lane id="Lane_1pshy69" />
    </bpmn:laneSet>
    <bpmn:callActivity id="Activity_0svk239" name="Story-Popup checken">
      <bpmn:extensionElements>
        <zeebe:calledElement processId="Process_056kd6t" propagateAllChildVariables="false" />
      </bpmn:extensionElements>
      <bpmn:incoming>Flow_1ctkn2b</bpmn:incoming>
      <bpmn:outgoing>Flow_0d81f97</bpmn:outgoing>
    </bpmn:callActivity>
    <bpmn:sequenceFlow id="Flow_15ks01v" sourceRef="StartEvent_1" targetRef="Activity_0b1ftek" />
    <bpmn:sequenceFlow id="Flow_02rfwbg" sourceRef="Activity_0c2ay3h" targetRef="Event_0u482rl" />
    <bpmn:sequenceFlow id="Flow_1ctkn2b" sourceRef="Activity_0b1ftek" targetRef="Activity_0svk239" />
    <bpmn:sequenceFlow id="Flow_0d81f97" sourceRef="Activity_0svk239" targetRef="Activity_0c2ay3h" />
    <bpmn:startEvent id="StartEvent_1">
      <bpmn:outgoing>Flow_15ks01v</bpmn:outgoing>
    </bpmn:startEvent>
    <bpmn:endEvent id="Event_0u482rl">
      <bpmn:incoming>Flow_02rfwbg</bpmn:incoming>
    </bpmn:endEvent>
    <bpmn:callActivity id="Activity_0b1ftek" name="AA">
      <bpmn:extensionElements>
        <zeebe:calledElement processId="Process_0bshks3" propagateAllChildVariables="false" />
      </bpmn:extensionElements>
      <bpmn:incoming>Flow_15ks01v</bpmn:incoming>
      <bpmn:outgoing>Flow_1ctkn2b</bpmn:outgoing>
    </bpmn:callActivity>
    <bpmn:callActivity id="Activity_0c2ay3h" name="CC">
      <bpmn:extensionElements>
        <zeebe:calledElement processId="Process_0vqqg2m" propagateAllChildVariables="false" />
      </bpmn:extensionElements>
      <bpmn:incoming>Flow_0d81f97</bpmn:incoming>
      <bpmn:outgoing>Flow_02rfwbg</bpmn:outgoing>
    </bpmn:callActivity>
  </bpmn:process>
  <bpmn:process id="Process_0bshks3" isExecutable="true">
    <bpmn:serviceTask id="Activity_10mlpa0" name="A">
      <bpmn:extensionElements>
        <zeebe:taskDefinition type="bar" />
        <zeebe:ioMapping>
          <zeebe:input source="" target="env" />
          <zeebe:input source="" target="app" />
        </zeebe:ioMapping>
      </bpmn:extensionElements>
    </bpmn:serviceTask>
  </bpmn:process>
  <bpmn:process id="Process_056kd6t" isExecutable="true">
    <bpmn:serviceTask id="Activity_1t5cglo" name="B">
      <bpmn:extensionElements>
        <zeebe:taskDefinition type="foo" />
      </bpmn:extensionElements>
    </bpmn:serviceTask>
  </bpmn:process>
  <bpmn:process id="Process_0vqqg2m" isExecutable="true">
    <bpmn:serviceTask id="Activity_1v6pb87" name="C">
      <bpmn:extensionElements>
        <zeebe:taskDefinition type="bar" />
      </bpmn:extensionElements>
    </bpmn:serviceTask>
  </bpmn:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Collaboration_1f5vyps">
      <bpmndi:BPMNShape id="Participant_18hshoa_di" bpmnElement="Participant_18hshoa" isHorizontal="true">
        <dc:Bounds x="249" y="70" width="839" height="370" />
        <bpmndi:BPMNLabel />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Lane_1gatmwv_di" bpmnElement="Lane_1gatmwv" isHorizontal="true">
        <dc:Bounds x="279" y="315" width="809" height="125" />
        <bpmndi:BPMNLabel />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Lane_0z9w44w_di" bpmnElement="Lane_0z9w44w" isHorizontal="true">
        <dc:Bounds x="279" y="70" width="809" height="125" />
        <bpmndi:BPMNLabel />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Lane_1pshy69_di" bpmnElement="Lane_1pshy69" isHorizontal="true">
        <dc:Bounds x="279" y="195" width="809" height="120" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_1kihcv5_di" bpmnElement="Activity_0svk239">
        <dc:Bounds x="630" y="340" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="_BPMNShape_StartEvent_2" bpmnElement="StartEvent_1">
        <dc:Bounds x="382" y="112" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_0u482rl_di" bpmnElement="Event_0u482rl">
        <dc:Bounds x="952" y="112" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_0n99hl5_di" bpmnElement="Activity_0b1ftek">
        <dc:Bounds x="470" y="90" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_0dkd24a_di" bpmnElement="Activity_0c2ay3h">
        <dc:Bounds x="790" y="90" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="Flow_15ks01v_di" bpmnElement="Flow_15ks01v">
        <di:waypoint x="418" y="130" />
        <di:waypoint x="470" y="130" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_02rfwbg_di" bpmnElement="Flow_02rfwbg">
        <di:waypoint x="890" y="130" />
        <di:waypoint x="952" y="130" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1ctkn2b_di" bpmnElement="Flow_1ctkn2b">
        <di:waypoint x="570" y="130" />
        <di:waypoint x="600" y="130" />
        <di:waypoint x="600" y="380" />
        <di:waypoint x="630" y="380" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_0d81f97_di" bpmnElement="Flow_0d81f97">
        <di:waypoint x="730" y="380" />
        <di:waypoint x="760" y="380" />
        <di:waypoint x="760" y="130" />
        <di:waypoint x="790" y="130" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape id="Participant_1lcoo0m_di" bpmnElement="Participant_1lcoo0m" isHorizontal="true">
        <dc:Bounds x="210" y="580" width="301" height="120" />
        <bpmndi:BPMNLabel />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_1pprjxf_di" bpmnElement="Activity_10mlpa0">
        <dc:Bounds x="311" y="600" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Participant_1donwvr_di" bpmnElement="Participant_1donwvr" isHorizontal="true">
        <dc:Bounds x="541" y="580" width="300" height="120" />
        <bpmndi:BPMNLabel />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_048iti1_di" bpmnElement="Activity_1t5cglo">
        <dc:Bounds x="651" y="600" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Participant_1f918a5_di" bpmnElement="Participant_1f918a5" isHorizontal="true">
        <dc:Bounds x="871" y="580" width="300" height="120" />
        <bpmndi:BPMNLabel />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_1fxhjok_di" bpmnElement="Activity_1v6pb87">
        <dc:Bounds x="981" y="600" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Group_0w380le_di" bpmnElement="Group_0w380le">
        <dc:Bounds x="160" y="550" width="1060" height="180" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="TextAnnotation_1lkonc6_di" bpmnElement="TextAnnotation_1lkonc6">
        <dc:Bounds x="380" y="80" width="570" height="50" />
        <bpmndi:BPMNLabel />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="TextAnnotation_0nt8b2x_di" bpmnElement="TextAnnotation_0nt8b2x">
        <dc:Bounds x="340" y="470" width="679" height="41" />
        <bpmndi:BPMNLabel />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="Association_1dkfaiy_di" bpmnElement="Association_1dkfaiy">
        <di:waypoint x="665" y="312" />
        <di:waypoint x="665" y="312" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Association_1i0bouy_di" bpmnElement="Association_1i0bouy">
        <di:waypoint x="516" y="550" />
        <di:waypoint x="440" y="511" />
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>
```

Good luck! :-)

**Comment by valb3r** [comment]
@drajovic Thanks for such a detailed description of the issue! 
We would like to offer you 6 month free usage of the plugin as the compensation for your time. Please write us an email to polybpmn@gdnext.com so that we can send you the 6 month free coupon in the reply.

**Comment by v20stepanenko** [comment]
@drajovic Thank you for your attention and time creating the NOK file. We have resolved this bug. Could you please install the attached plugin from this message and try it again?
[polybpmn-intellij-plugin.zip](https://github.com/GDNext-GmbH/polybpmn/files/12444885/polybpmn-intellij-plugin.zip)

**Comment by drajovic** [comment]
Sorry for the delayed answer. Good news!  I confirm that the new plugin now successfully parses all of my diagrams and displays the correct visualization. On many diagrams I can now see notifications in following form:

````
- Can't parse edges with diagram id: 
Association_1793qj1_di, 
Association_1832yel_di, 
...,
Association_1832yel_di
````
Note that some associations appear several times in the message.
But other than that I can live perfectly with it. ;-)  
Thanks a lot for the great support!
dean
